apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - db.yaml
  - release.yaml

#secretGenerator:
#  - name: ghost-db-secrets
#    literals:
#      - root=VeryStrongRootPass123!
#      - xtrabackup=BackupPass123!
#      - monitor=MonitorPass123!
#      - clustercheck=ClusterCheckPass123!
#      - operator=OperatorPass123!
#    options:
#      disableNameSuffixHash: true
