apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/ghost
  - namespace.yaml
  # Не забудьте додати файл створення бази для staging, якщо він є окремим файлом
  # - mariadb-staging.yaml
namespace: staging

patches:
  - target:
      kind: HelmRelease
      name: ghost
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: ghost
      spec:
        values:
          url: "http://ghost-staging.k8s.com822.dom"
          ingress:
            enabled: true
            hosts:
              - host: ghost-staging.k8s.com822.dom
                paths:
                  - path: /
                    pathType: Prefix
