apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/ghost
 
namespace: staging

patches:
  - target:
      kind: HelmRelease
      name: ghost
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: ghost
      spec:
        valuesFrom:
          - kind: Secret
            name: ghost-values-override
            valuesKey: values.yaml
        values:
          secrets:
            db:
              create: true
            mail:
              create: true


          url: "http://ghost-staging.k8s.com822.dom"
          ingress:
            enabled: true
            hosts:
              - host: ghost-staging.k8s.com822.dom
                paths:
                  - path: /
                    pathType: Prefix
