apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controllers/namespace.yaml
  - controllers/mariadb.yaml
  - configs/bitnami-repo.yaml
  - configs/minio-repo.yaml
#  - controllers/pxc-rbac.yaml
  - controllers/minio.yaml
