apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/infrastructure.yaml
  - configs/bitnami-repo.yaml
  - configs/mariadb-repo.yaml
  - controllers/cert-manager.yaml
  - configs/cluster-issuer.yaml