apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/infrastructure.yaml
  - configs/bitnami-repo.yaml
  - configs/mariadb-repo.yaml
  - namespaces/production.yaml
  - namespaces/staging.yaml
  - controllers/mariadb.yaml
