apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghost.fullname" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ghost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ghost.selectorLabels" . | nindent 8 }}
    spec:
      # --- INIT CONTAINER (Тільки якщо S3 увімкнено) ---
      {{- if .Values.storage.s3.enabled }}
      initContainers:
        - name: install-s3-adapter
          image: node:18-slim
          securityContext:
            runAsUser: 0 # Root потрібен для chown
          command:
            - sh
            - -c
            - |
              cd /plugin-volume
              rm -rf *

              # Повертаємось до офіційного адаптера
              npm pack ghost-storage-adapter-s3

              tar -xzf *.tgz --strip-components=1
              rm *.tgz
              npm install --omit=dev --ignore-scripts --no-bin-links
              chown -R 1000:1000 .
          volumeMounts:
            - name: s3-adapter-volume
              mountPath: /plugin-volume
      {{- end }}


      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 2368
              protocol: TCP

          # --- ЗМІННІ СЕРЕДОВИЩА (Налаштування) ---
          env:

            - name: url
              value: {{ .Values.url | quote }}
            - name: NODE_ENV
              value: production
            - name: imageOptimization__resize
              value: "false"

    # База Даних (MariaDB)
            - name: database__client
              value: {{ .Values.externalDatabase.client | quote }}
            - name: database__connection__host
              value: {{ .Values.externalDatabase.host | quote }}
            - name: database__connection__port
              value: {{ .Values.externalDatabase.port | quote }}
            - name: database__connection__user
              value: {{ .Values.externalDatabase.user | quote }}
            - name: database__connection__password
              value: {{ .Values.externalDatabase.password | quote }}
            - name: database__connection__database
              value: {{ .Values.externalDatabase.database | quote }}

  # === AWS S3 CONFIG ===
            - name: storage__active
              value: "s3"
  
  # Регіон, який ви обрали при створенні бакета (напр. eu-central-1)
            - name: storage__s3__region
              value: "eu-north-1"

  # Точне ім'я бакета
            - name: storage__s3__bucket
              value: "ghost-exam-baket"

  # Ключі, які ви отримали в IAM (Step 3)
            - name: storage__s3__accessKeyID
              valueFrom:
                secretKeyRef:
                  name: ghost-aws-secrets
                  key: access-key
            - name: storage__s3__secretAccessKey
              valueFrom:
                secretKeyRef:
                  name: ghost-aws-secrets
                  key: secret-key
  # Це корисно залишити, щоб Sharp не "їв" пам'ять
            - name: imageOptimization__resize
              value: "false"
            - name: AWS_ACCESS_KEY_ID        # <--- Стандартна назва
              valueFrom:
                secretKeyRef:
                  name: ghost-aws-secrets
                  key: access-key

            - name: AWS_SECRET_ACCESS_KEY    # <--- Стандартна назва
              valueFrom:
                secretKeyRef:
                name: ghost-aws-secrets
                key: secret-key

            - name: AWS_DEFAULT_REGION       # <--- Стандартна назва
              value: "eu-north-1"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: s3-adapter-volume
              # Цей шлях критично важливий, він каже Ghost'у, де лежить "драйвер"
              mountPath: /var/lib/ghost/content/adapters/storage/s3
      volumes:

     # Том для контенту (PVC)
        {{- if .Values.persistence.enabled }}
        - name: ghost-content
          persistentVolumeClaim:
            claimName: {{ include "ghost.fullname" . }}
        {{- end }}

        # Том для адаптера (спільний з init-контейнером)
        {{- if .Values.storage.s3.enabled }}
        - name: s3-adapter-volume
          emptyDir: {}
        {{- end }}
