{{- /* 1. Секрет Бази Даних */ -}}
{{- if .Values.secrets.db.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.db.name }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
type: Opaque
stringData:
  root: {{ .Values.secrets.db.values.root | quote }}
  password: {{ .Values.secrets.db.values.password | quote }}
{{- end }}

---

{{- /* 2. Секрет Пошти */ -}}
{{- if .Values.secrets.mail.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mail.name }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
type: Opaque
stringData:
  mail-pass: {{ .Values.secrets.mail.values.password | quote }}
{{- end }}

---

{{- /* 3. Секрет S3 */ -}}
{{- if .Values.secrets.s3.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.s3.name }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.secrets.s3.values.accessKey | quote }}
  secret-key: {{ .Values.secrets.s3.values.secretKey | quote }}
{{- end }}
