apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2368
      protocol: TCP
  selector:
    app.kubernetes.io/name: ghost-exam
    app.kubernetes.io/instance: ghost