apiVersion: v1
kind: Service
metadata:
 
  name: {{ include "ghost.fullname" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2368
      protocol: TCP
      name: http
  selector:
   
    {{- include "ghost.selectorLabels" . | nindent 4 }}
