apiVersion: v1
kind: Service
metadata:
  # Використовуємо fullname, щоб співпадало з тим, що шукає Ingress
  name: {{ include "ghost.fullname" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2368
      protocol: TCP
      name: http
  selector:
    # Використовуємо той самий шаблон селектора, що і в Deployment
    {{- include "ghost.selectorLabels" . | nindent 4 }}
